### ISSUE TITLE
onlyoffice预览与编辑代码，麻烦你看一下有没有用

### ISSUE THREAD

**Issue by 13414897882** [zhtengw/kodexplorer-plugins#1]
onlyoffice的app.php代码
<?php

class onlyofficePlugin extends PluginBase{
	function __construct(){
		parent::__construct();
	}
	public function regiest(){
		$this->hookRegiest(array(
			'user.commonJs.insert' => 'onlyofficePlugin.echoJs'
		));
	}
	public function echoJs($st,$act){
		if($this->isFileExtence($st,$act)){
			$this->echoFile('static/main.js');
		}
	}

	public function index(){
		$fileName = get_path_this(rawurldecode($this->in['path']));
		$pathIsUrl = false;
		if(substr($this->in['path'],0,4) == 'http'){
			$path = $fileUrl = $this->in['path'];
			$pathIsUrl = true;
		}else{
			$path = _DIR($this->in['path']);
			$fileUrl  = _make_file_proxy($path);
			if (!file_exists($path)) {
				show_tips(LNG('not_exists'));
			}
		}

		$appConfig = $this->options();
		$ext = get_path_ext($path);
		$option = array(
			'officeApi'		=> $this->pluginApi,
			'officeFile'	=> rawurlencode($this->in['path']),
			'url'			=> $fileUrl,
			'key'			=> $pathIsUrl?rand_string(10):@md5_file($path),
			'time'			=> $pathIsUrl?rand_string(10):@filemtime($path),
			'fileType'		=> $this->fileTypeAlias($ext),
			'title'			=> $fileName,
			'documentType'	=> $this->appType($ext),
			'user'			=> $_SESSION['kodUser']['name'],
			'userID'		=> $_SESSION['kodUser']['userID'],
			'mode'			=> 'view',
			'lang'			=> I18n::getType(),
		);

		//只读
		if($GLOBALS['kodPathType'] == KOD_USER_SHARE){						
		}else if(!$pathIsUrl){
			if(check_file_writable_user($path)){//可读写权限检测
				$option['mode'] = 'edit';
				$option['key']  = md5($path.$option['time']);
				$option['callbackUrl'] = $option['officeApi'].'save&path='
					.$option['officeFile'].'&accessToken='.access_token_get();
			}
		}else if(isset($this->in['saveCallback'])){
			$option['officeFile'] .= rawurlencode('&saveCallback='.$this->in['saveCallback'].'&name=/'.$fileName);
			if(substr($this->in['saveCallback'],0,4) == 'http'){
				$option['mode'] = 'edit';
				$option['callbackUrl'] =  $option['officeApi'].'save&path='
					.$option['officeFile'].'&accessToken='.access_token_get();
			}
		}

		//移动端预览模式
		if( is_wap() && $appConfig['wapViewMode'] == 'view'){
			$option['mode'] = 'view';
		}

		Hook::filter('onlyoffice.fileGet.filter',$option);//数据处理
		$this->resetAppHost($option);
		//旧版本
		if( defined("OFFICE_KOD_SERVER")){
			$fileLink  = $option['officeApi'].'save&type=explorer/fileProxy&path='.$option['officeFile'];
			$appRandom = rand_string(10);
			$officeUrl = OFFICE_KOD_SERVER.rawurlencode($fileLink)
						.'&lang='.I18n::getType().'&appType=desktop'
						.'&appMode='.$option['mode'].'&access_token='.access_token_get()
						.'&file_time='.$option['time'].'&key='.$option['key']
						.'&user_id='.$option['userID'].'&user_name='.$option['user']
						.'&app_id='.OFFICE_KOD_APP_ID.'&app_s='.$appRandom.'&app_v='.md5($appRandom.OFFICE_KOD_APP_KEY);

			header("Location: ".$officeUrl);
			return;
		}
		//新版本
		$fileName.= ' - '.LNG('kod_name').LNG('kod_power_by');
		include($this->pluginPath.'php/template.html');
	}
	private function options(){
		$appConfig = $this->getConfig();

		//未填写;则默认和kod同服务器
		if(!$appConfig['serverApi']){
			$host = rtrim(get_host(),'/');
			if(strrpos($host,':') > 5){
				$host = substr($host,0,strrpos($host,':'));
			}
			$appConfig['serverApi'] = $host.':8001/web/';
		}

		if( !trim($appConfig['cdnPath']) ){
			$appConfig['cdnPath'] = $appConfig['serverApi'];
		}
		if( !trim($appConfig['kodAppHost']) ){
			$appConfig['kodAppHost'] = APP_HOST;
		}
		$appConfig['cdnPath'] = rtrim($appConfig['cdnPath'],'/').'/';
		$appConfig['serverApi'] = rtrim($appConfig['serverApi'],'/').'/';
		if(!$GLOBALS['isRoot']){
			/**
			 * 	下载&打印&导出:权限取决于文件是否可以下载;(管理员无视所有权限拦截)
			 * 	1. 当前用户是否允许下载
			 * 	2. 所在群组文件，用户在群组内的权限是否可下载
			 * 	3. 文件分享,限制了下载
			 */
			if($GLOBALS['auth'] && !$GLOBALS['auth']['explorer.fileDownload']){
				$appConfig['canDownload'] = false;
			}
			if( $GLOBALS['kodShareInfo'] && $GLOBALS['kodShareInfo']['notDownload'] == '1'){
				$appConfig['canDownload'] = false;
			}
			if( $GLOBALS['kodPathRoleGroupAuth'] && !$GLOBALS['kodPathRoleGroupAuth']['explorer.fileDownload']){
				$appConfig['canDownload'] = false;
			}
		}
		//特殊处理
		$temp = Hook::trigger("onlyofficeOptions",$appConfig);
		if(is_array($temp)){
			$appConfig = $temp;
		}
		// $appConfig['info'] = array(
		// 	'versionHash' => systemOption('versionHash'),
		// 	'versionHashUser' => systemOption('versionHashUser'),
		// );
		return $appConfig;
	}

	public function check(){
		$appConfig = $this->options();
		//kod访问office服务器;网络检测;office提交保存文件时；kod通过url从office服务器获取文件并保存
		if(isset($this->in['fileSave'])){
			$result = curl_get_contents($appConfig['serverApi'].'/sdkjs/common/AllFonts.js');
			if( $result  && strlen($result) > 5000 ){
				echo 'success';
			}
			exit;
		}
		//office服务器访问kod;网络检测
		if(isset($this->in['output'])){
			echo 'success';
			exit;
		}
		
		$kod = array(
			"url" => APP_HOST,
			"callbackUrl" => $this->pluginApi.'check&output=&accessToken='.access_token_get()			
		);
		$this->resetAppHost($kod);
		include($this->pluginPath.'php/check.html');
	}

	private function resetAppHost(&$data){
		$appConfig = $this->options();
		if( $appConfig['kodAppHost'] == APP_HOST ){
			return;
		}
		$replace = array('officeFile','url','officeApi','callbackUrl');
		foreach ($replace as $key) {
			if(is_string($data)) {
				$data = str_replace(APP_HOST,$appConfig['kodAppHost'],$data);
				return $data;
			}
			if(isset($data[$key])){
				$data[$key] = str_replace(APP_HOST,$appConfig['kodAppHost'],$data[$key]);
			}
		}
	}

	public function save(){
		$this->log(array('call save',$this->in));
		//手动保存
		if(isset($this->in['EditorBin'])){
			$this->saveFile($this->in['EditorBin']);
			return;
		}
		if($this->in['type'] == 'explorer/fileProxy'){
			if(substr($this->in['path'],0,4) == 'http'){
				header('Location: '.$this->in['path']);
				exit;
			}
			$savePath = _DIR($this->in['path']);
			//var_dump(file_exists($savePath),$savePath);exit;
			file_put_out($savePath,false);
			exit;
		}

		if (($bodyStream = file_get_contents('php://input'))===FALSE){
			$this->jsonPutout(array('error'=>'Bad Request'),'bodyStream null');
		}
		$data = json_decode($bodyStream,true);
		if ($data === NULL){
			$this->jsonPutout(array('error'=>'Bad Response'),'bodyStream json_decode error');
		}
		$trackerStatus = array(
			0 => 'NotFound',
			1 => 'Editing',
			2 => 'MustSave',
			3 => 'Corrupted',
			4 => 'Closed'
			//4 => 'Editing'
		);
		$result = array('error'=>0,'action'=>$trackerStatus[$data["status"]]);
		switch ($trackerStatus[$data["status"]]){
			case "MustSave":
			case "Corrupted":
				Hook::trigger('explorer.fileSave');
				Hook::filter('onlyoffice.fileSave.filter',$data);
				$this->resetAppHost($data);
				$data['saveResult'] = $this->saveFile($data["url"]);
				$result["c"] = "saved";
				$result['status'] = '0';
				$result['status'] = 'success';
				break;
			default:break;
		}
		$this->jsonPutout($result,$data);
	}

	private function saveFile($resultUrl){
		$options = $this->getConfig();
		//支持https转发的情况
	    if(substr($options['serverApi'],0,8) == 'https://'){
	        $resultUrl = str_replace("http://","https://",$resultUrl);
	    }
	    
		//同一台机器,保存时获取临时文件
		if( !$options['serverApi'] ){
			$host = get_url_root($resultUrl);
			$resultUrl = str_replace($host,'http://127.0.0.1:8001/',$resultUrl);
		}
				
		$this->log(array('saveFile',$resultUrl,$this->in['path']));
		$path = $this->in['path'];
		if(strstr($path,'&saveCallback=')){
			$param = parse_url_query($path);
			if(!isset($param['saveCallback'])){
				$this->jsonPutout(array('error'=>'Bad Request'),'saveCallback null');
			}
			$callback = rawurldecode($param['saveCallback']).'&fileUrl='.rawurlencode($resultUrl);
			$this->log(array('saveFileApiCallback',$callback,$param));
			$return = file_get_contents($callback);
			$this->log(array('saveFileApiCallback-return',$return));
			return $callback;
		}else{
			$savePath = _DIR($path);
			if ( !path_writeable($savePath) ){
				$this->jsonPutout(array('error'=>'no_permission_write'),'no_permission_write');
			}
			$this->log(array('saveFileLocalStart',$resultUrl,$savePath));
			return file_download_this($resultUrl,$savePath);
		}
	}
	private function log($log){
		$appConfig = $this->getConfig();
		if($appConfig['debug']){
			write_log($log,'onlyoffice');
		}
	}

	private function jsonPutout($info,$log){
		@ob_end_clean();
		@header( 'Content-Type: application/json; charset==utf-8');
		@header( 'X-Robots-Tag: noindex' );
		@header( 'X-Content-Type-Options: nosniff' );
		$this->log(array('jsonPutout',$info,$log));
		echo json_encode($info);
		exit;
	}

	//格式转义
	private function fileTypeAlias($ext){
		if(strpos(".docm.dotm.dot.wps.wpt",'.'.$ext) !== false){
			$ext = 'doc';
		}else if(strpos(".xlt.xltx.xlsm.dotx.et.ett",'.'.$ext) !== false){
			$ext = 'xls';
		}else if(strpos(".pot.potx.pptm.ppsm.potm.dps.dpt",'.'.$ext) !== false){
			$ext = 'ppt';
		}
		return $ext;
	}
	private function appType($ext){
		$typeArr = array(
			'text' => array('docx','doc','odt','rtf','mht','djvu','fb2','xps',
				'docm','dotm','dot','dotx', 'wps','wpt','pdf'),
			'spreadsheet' => array('xls','xlsx','ods','csv','xlt','xltx','xlsm',  'et','ett'),
			'presentation' => array('pps','ppsx','ppt','pptx','odp','pot',
				'potx','pptm','ppsm','potm','dps','dpt'),
		);
		foreach ($typeArr as $key => $value) {
			if(in_array($ext,$value)){
				return $key;
			}
		}
		show_tips("暂不支持该扩展名!");
		return '';
	}

	public function view(){
		$path = $this->filePath($this->in['path']);
		$viewFile = TEMP_PATH.$this->pluginName.'/'.hash_path($path).'.pdf';
		if(!file_exists($viewFile)){
			$json = $this->convert($path,'pdf');
			if($json['fileUrl']){
				$content = file_get_contents($json['fileUrl']);
				mk_dir(get_path_father($viewFile));
				file_put_contents($viewFile,$content);
			}	
		}
		if(!file_exists($viewFile)){
			show_tips("您的文档中存在无法解析的内容。请尝试下载到本地进行操作。");
		}
		
		$fileUrl  = _make_file_proxy($viewFile);
		if(file_exists(PLUGIN_DIR.'pdfjs')){			
			$fileName = get_path_this(rawurldecode($this->in['path']));
			$fileName.= ' - '.LNG('kod_name').LNG('kod_power_by');
			$this->pluginHost = get_path_father($this->pluginHost).'pdfjs/';
			include(PLUGIN_DIR.'pdfjs/php/pdf.php');
		}else{
			header("Location: ".$fileUrl);
		}
	}

	// convert https://api.onlyoffice.com/editors/conversionapi
	// view    https://api.onlyoffice.com/editors/try
	private function convert($path,$ext){
		$appConfig = $this->getConfig();
		$host  = get_url_root($appConfig['serverApi']);
		$api   = rtrim($host,'/')."/ConvertService.ashx";
		$param = array(
			//"async"         => true,
			"url"           => _make_file_proxy($path),
			"outputtype"    => $ext,
			"filetype"      => get_path_ext($path),
			"title"         => "file",
			"key"           => md5("office".hash_path($path))
		);
		$this->resetAppHost($param);
		$opts = array(
			'http' => array(
				'method'  => 'POST',
				'timeout' => 500,
				'header'  => "Content-type: application/json\r\nAccept: application/json\r\n",
				'content' => json_encode($param)
			)
		);
		$response = file_get_contents($api,false,stream_context_create($opts));
		return json_decode($response,true);
	}
}

**Comment by 13414897882** [comment]
onlyoffice的app.php代码
<?php

class onlyofficePlugin extends PluginBase{
	function __construct(){
		parent::__construct();
	}
	public function regiest(){
		$this->hookRegiest(array(
			'user.commonJs.insert' => 'onlyofficePlugin.echoJs'
		));
	}
	public function echoJs($st,$act){
		if($this->isFileExtence($st,$act)){
			$this->echoFile('static/main.js');
		}
	}

	public function index(){
		$fileName = get_path_this(rawurldecode($this->in['path']));
		$pathIsUrl = false;
		if(substr($this->in['path'],0,4) == 'http'){
			$path = $fileUrl = $this->in['path'];
			$pathIsUrl = true;
		}else{
			$path = _DIR($this->in['path']);
			$fileUrl  = _make_file_proxy($path);
			if (!file_exists($path)) {
				show_tips(LNG('not_exists'));
			}
		}

		$appConfig = $this->options();
		$ext = get_path_ext($path);
		$option = array(
			'officeApi'		=> $this->pluginApi,
			'officeFile'	=> rawurlencode($this->in['path']),
			'url'			=> $fileUrl,
			'key'			=> $pathIsUrl?rand_string(10):@md5_file($path),
			'time'			=> $pathIsUrl?rand_string(10):@filemtime($path),
			'fileType'		=> $this->fileTypeAlias($ext),
			'title'			=> $fileName,
			'documentType'	=> $this->appType($ext),
			'user'			=> $_SESSION['kodUser']['name'],
			'userID'		=> $_SESSION['kodUser']['userID'],
			'mode'			=> 'view',
			'lang'			=> I18n::getType(),
		);

		//只读
		if($GLOBALS['kodPathType'] == KOD_USER_SHARE){						
		}else if(!$pathIsUrl){
			if(check_file_writable_user($path)){//可读写权限检测
				$option['mode'] = 'edit';
				$option['key']  = md5($path.$option['time']);
				$option['callbackUrl'] = $option['officeApi'].'save&path='
					.$option['officeFile'].'&accessToken='.access_token_get();
			}
		}else if(isset($this->in['saveCallback'])){
			$option['officeFile'] .= rawurlencode('&saveCallback='.$this->in['saveCallback'].'&name=/'.$fileName);
			if(substr($this->in['saveCallback'],0,4) == 'http'){
				$option['mode'] = 'edit';
				$option['callbackUrl'] =  $option['officeApi'].'save&path='
					.$option['officeFile'].'&accessToken='.access_token_get();
			}
		}

		//移动端预览模式
		if( is_wap() && $appConfig['wapViewMode'] == 'view'){
			$option['mode'] = 'view';
		}

		Hook::filter('onlyoffice.fileGet.filter',$option);//数据处理
		$this->resetAppHost($option);
		//旧版本
		if( defined("OFFICE_KOD_SERVER")){
			$fileLink  = $option['officeApi'].'save&type=explorer/fileProxy&path='.$option['officeFile'];
			$appRandom = rand_string(10);
			$officeUrl = OFFICE_KOD_SERVER.rawurlencode($fileLink)
						.'&lang='.I18n::getType().'&appType=desktop'
						.'&appMode='.$option['mode'].'&access_token='.access_token_get()
						.'&file_time='.$option['time'].'&key='.$option['key']
						.'&user_id='.$option['userID'].'&user_name='.$option['user']
						.'&app_id='.OFFICE_KOD_APP_ID.'&app_s='.$appRandom.'&app_v='.md5($appRandom.OFFICE_KOD_APP_KEY);

			header("Location: ".$officeUrl);
			return;
		}
		//新版本
		$fileName.= ' - '.LNG('kod_name').LNG('kod_power_by');
		include($this->pluginPath.'php/template.html');
	}
	private function options(){
		$appConfig = $this->getConfig();

		//未填写;则默认和kod同服务器
		if(!$appConfig['serverApi']){
			$host = rtrim(get_host(),'/');
			if(strrpos($host,':') > 5){
				$host = substr($host,0,strrpos($host,':'));
			}
			$appConfig['serverApi'] = $host.':8001/web/';
		}

		if( !trim($appConfig['cdnPath']) ){
			$appConfig['cdnPath'] = $appConfig['serverApi'];
		}
		if( !trim($appConfig['kodAppHost']) ){
			$appConfig['kodAppHost'] = APP_HOST;
		}
		$appConfig['cdnPath'] = rtrim($appConfig['cdnPath'],'/').'/';
		$appConfig['serverApi'] = rtrim($appConfig['serverApi'],'/').'/';
		if(!$GLOBALS['isRoot']){
			/**
			 * 	下载&打印&导出:权限取决于文件是否可以下载;(管理员无视所有权限拦截)
			 * 	1. 当前用户是否允许下载
			 * 	2. 所在群组文件，用户在群组内的权限是否可下载
			 * 	3. 文件分享,限制了下载
			 */
			if($GLOBALS['auth'] && !$GLOBALS['auth']['explorer.fileDownload']){
				$appConfig['canDownload'] = false;
			}
			if( $GLOBALS['kodShareInfo'] && $GLOBALS['kodShareInfo']['notDownload'] == '1'){
				$appConfig['canDownload'] = false;
			}
			if( $GLOBALS['kodPathRoleGroupAuth'] && !$GLOBALS['kodPathRoleGroupAuth']['explorer.fileDownload']){
				$appConfig['canDownload'] = false;
			}
		}
		//特殊处理
		$temp = Hook::trigger("onlyofficeOptions",$appConfig);
		if(is_array($temp)){
			$appConfig = $temp;
		}
		// $appConfig['info'] = array(
		// 	'versionHash' => systemOption('versionHash'),
		// 	'versionHashUser' => systemOption('versionHashUser'),
		// );
		return $appConfig;
	}

	public function check(){
		$appConfig = $this->options();
		//kod访问office服务器;网络检测;office提交保存文件时；kod通过url从office服务器获取文件并保存
		if(isset($this->in['fileSave'])){
			$result = curl_get_contents($appConfig['serverApi'].'/sdkjs/common/AllFonts.js');
			if( $result  && strlen($result) > 5000 ){
				echo 'success';
			}
			exit;
		}
		//office服务器访问kod;网络检测
		if(isset($this->in['output'])){
			echo 'success';
			exit;
		}
		
		$kod = array(
			"url" => APP_HOST,
			"callbackUrl" => $this->pluginApi.'check&output=&accessToken='.access_token_get()			
		);
		$this->resetAppHost($kod);
		include($this->pluginPath.'php/check.html');
	}

	private function resetAppHost(&$data){
		$appConfig = $this->options();
		if( $appConfig['kodAppHost'] == APP_HOST ){
			return;
		}
		$replace = array('officeFile','url','officeApi','callbackUrl');
		foreach ($replace as $key) {
			if(is_string($data)) {
				$data = str_replace(APP_HOST,$appConfig['kodAppHost'],$data);
				return $data;
			}
			if(isset($data[$key])){
				$data[$key] = str_replace(APP_HOST,$appConfig['kodAppHost'],$data[$key]);
			}
		}
	}

	public function save(){
		$this->log(array('call save',$this->in));
		//手动保存
		if(isset($this->in['EditorBin'])){
			$this->saveFile($this->in['EditorBin']);
			return;
		}
		if($this->in['type'] == 'explorer/fileProxy'){
			if(substr($this->in['path'],0,4) == 'http'){
				header('Location: '.$this->in['path']);
				exit;
			}
			$savePath = _DIR($this->in['path']);
			//var_dump(file_exists($savePath),$savePath);exit;
			file_put_out($savePath,false);
			exit;
		}

		if (($bodyStream = file_get_contents('php://input'))===FALSE){
			$this->jsonPutout(array('error'=>'Bad Request'),'bodyStream null');
		}
		$data = json_decode($bodyStream,true);
		if ($data === NULL){
			$this->jsonPutout(array('error'=>'Bad Response'),'bodyStream json_decode error');
		}
		$trackerStatus = array(
			0 => 'NotFound',
			1 => 'Editing',
			2 => 'MustSave',
			3 => 'Corrupted',
			4 => 'Closed'
			//4 => 'Editing'
		);
		$result = array('error'=>0,'action'=>$trackerStatus[$data["status"]]);
		switch ($trackerStatus[$data["status"]]){
			case "MustSave":
			case "Corrupted":
				Hook::trigger('explorer.fileSave');
				Hook::filter('onlyoffice.fileSave.filter',$data);
				$this->resetAppHost($data);
				$data['saveResult'] = $this->saveFile($data["url"]);
				$result["c"] = "saved";
				$result['status'] = '0';
				$result['status'] = 'success';
				break;
			default:break;
		}
		$this->jsonPutout($result,$data);
	}

	private function saveFile($resultUrl){
		$options = $this->getConfig();
		//支持https转发的情况
	    if(substr($options['serverApi'],0,8) == 'https://'){
	        $resultUrl = str_replace("http://","https://",$resultUrl);
	    }
	    
		//同一台机器,保存时获取临时文件
		if( !$options['serverApi'] ){
			$host = get_url_root($resultUrl);
			$resultUrl = str_replace($host,'http://127.0.0.1:8001/',$resultUrl);
		}
				
		$this->log(array('saveFile',$resultUrl,$this->in['path']));
		$path = $this->in['path'];
		if(strstr($path,'&saveCallback=')){
			$param = parse_url_query($path);
			if(!isset($param['saveCallback'])){
				$this->jsonPutout(array('error'=>'Bad Request'),'saveCallback null');
			}
			$callback = rawurldecode($param['saveCallback']).'&fileUrl='.rawurlencode($resultUrl);
			$this->log(array('saveFileApiCallback',$callback,$param));
			$return = file_get_contents($callback);
			$this->log(array('saveFileApiCallback-return',$return));
			return $callback;
		}else{
			$savePath = _DIR($path);
			if ( !path_writeable($savePath) ){
				$this->jsonPutout(array('error'=>'no_permission_write'),'no_permission_write');
			}
			$this->log(array('saveFileLocalStart',$resultUrl,$savePath));
			return file_download_this($resultUrl,$savePath);
		}
	}
	private function log($log){
		$appConfig = $this->getConfig();
		if($appConfig['debug']){
			write_log($log,'onlyoffice');
		}
	}

	private function jsonPutout($info,$log){
		@ob_end_clean();
		@header( 'Content-Type: application/json; charset==utf-8');
		@header( 'X-Robots-Tag: noindex' );
		@header( 'X-Content-Type-Options: nosniff' );
		$this->log(array('jsonPutout',$info,$log));
		echo json_encode($info);
		exit;
	}

	//格式转义
	private function fileTypeAlias($ext){
		if(strpos(".docm.dotm.dot.wps.wpt",'.'.$ext) !== false){
			$ext = 'doc';
		}else if(strpos(".xlt.xltx.xlsm.dotx.et.ett",'.'.$ext) !== false){
			$ext = 'xls';
		}else if(strpos(".pot.potx.pptm.ppsm.potm.dps.dpt",'.'.$ext) !== false){
			$ext = 'ppt';
		}
		return $ext;
	}
	private function appType($ext){
		$typeArr = array(
			'text' => array('docx','doc','odt','rtf','mht','djvu','fb2','xps',
				'docm','dotm','dot','dotx', 'wps','wpt','pdf'),
			'spreadsheet' => array('xls','xlsx','ods','csv','xlt','xltx','xlsm',  'et','ett'),
			'presentation' => array('pps','ppsx','ppt','pptx','odp','pot',
				'potx','pptm','ppsm','potm','dps','dpt'),
		);
		foreach ($typeArr as $key => $value) {
			if(in_array($ext,$value)){
				return $key;
			}
		}
		show_tips("暂不支持该扩展名!");
		return '';
	}


	public function view(){
		$path = $this->filePath($this->in['path']);
		$viewFile = TEMP_PATH.$this->pluginName.'/'.hash_path($path).'.pdf';
		if(!file_exists($viewFile)){
			$json = $this->convert($path,'pdf');
			if($json['fileUrl']){
				$content = file_get_contents($json['fileUrl']);
				mk_dir(get_path_father($viewFile));
				file_put_contents($viewFile,$content);
			}	
		}
		if(!file_exists($viewFile)){
			show_tips("您的文档中存在无法解析的内容。请尝试下载到本地进行操作。");
		}
		
		$fileUrl  = _make_file_proxy($viewFile);
		if(file_exists(PLUGIN_DIR.'pdfjs')){			
			$fileName = get_path_this(rawurldecode($this->in['path']));
			$fileName.= ' - '.LNG('kod_name').LNG('kod_power_by');
			$this->pluginHost = get_path_father($this->pluginHost).'pdfjs/';
			include(PLUGIN_DIR.'pdfjs/php/pdf.php');
		}else{
			header("Location: ".$fileUrl);
		}
	}

	// convert https://api.onlyoffice.com/editors/conversionapi
	// view    https://api.onlyoffice.com/editors/try
	private function convert($path,$ext){
		$appConfig = $this->getConfig();
		$host  = get_url_root($appConfig['serverApi']);
		$api   = rtrim($host,'/')."/ConvertService.ashx";
		$param = array(
			//"async"         => true,
			"url"           => _make_file_proxy($path),
			"outputtype"    => $ext,
			"filetype"      => get_path_ext($path),
			"title"         => "file",
			"key"           => md5("office".hash_path($path))
		);
		$this->resetAppHost($param);
		$opts = array(
			'http' => array(
				'method'  => 'POST',
				'timeout' => 500,
				'header'  => "Content-type: application/json\r\nAccept: application/json\r\n",
				'content' => json_encode($param)
			)
		);
		$response = file_get_contents($api,false,stream_context_create($opts));
		return json_decode($response,true);
	}
}

**Comment by zhtengw** [comment]
……你这样复制上来有点牛逼。最好用"```"把代码段括起来吧

**Comment by 13414897882** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 中午11:45
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] onlyoffice预览与编辑代码，麻烦你看一下有没有用 (#1)




……你这样复制上来有点牛逼。最好用"```"把代码段括起来吧

**Comment by 13414897882** [comment]
你好，我传个附件给你看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 中午11:45
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] onlyoffice预览与编辑代码，麻烦你看一下有没有用 (#1)




……你这样复制上来有点牛逼。最好用"```"把代码段括起来吧

**Comment by 13414897882** [comment]
你好，我用邮箱传附件给你了，麻烦你看一下

**Comment by zhtengw** [comment]
你邮件发过来也是一样未格式化揉成一团的代码。没关系了，我看完了，确实非常有用。我已经把改过的插件push上来了。我这里测试感觉还行，你试试看。
PS: github的共同作者功能不会用啊，我在commit里加了你作为共同作者，可是并没有正常显示成合作人。

**Comment by 13414897882** [comment]
我发过去的是一个php的文件，用nopedat++这个软件打开

**Comment by zhtengw** [comment]
> 
> 
> 我发过去的是一个php的文件，用nopedat++这个软件打开

哦？那没收到，没关系了，已经整理好了。非常有用。

**Comment by zhtengw** [comment]
https://github.com/zhtengw/kodexplorer-plugins/commit/a4d91277ed084c3529a0417a23f24d2c119a8bd9

**Comment by 13414897882** [comment]
这代码也不是我写的，我不会编程，cad的插件也有代码，psd的插件也是有代码的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 下午3:14
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] onlyoffice预览与编辑代码，麻烦你看一下有没有用 (#1)




你邮件发过来也是一样未格式化揉成一团的代码。没关系了，我看完了，确实非常有用。我已经把改过的插件push上来了。我这里测试感觉还行，你试试看。
 PS: github的共同作者功能不会用啊，我在commit里加了你作为共同作者，可是并没有正常显示成合作人。
