### ISSUE TITLE
为啥我打开你的所有插件都是空白的窗口

### ISSUE THREAD

**Issue by sleikang** [zhtengw/kodexplorer-plugins#11]
为啥我打开你的所有插件都是空白的窗口，所有插件都是空白界面

**Comment by zhtengw** [comment]
控制台什么提示呢，kodexplorer和kodbox的插件是不同的，需要下对应版本

**Comment by sleikang** [comment]
版本都是对应的，应该是我的源站是84端口，CDN来做强制HTTPS跳转，无法找到插件一些文件的绝对访问路径，但是官方自带插件没有问题

**Comment by 13414897882** [comment]
这是来自QQ邮箱的自动回复邮件。谢谢你的邮件，我会尽快查看
