### ISSUE TITLE
onlyoffice 同步

### ISSUE THREAD

**Issue by oyzbmmmm** [zhtengw/kodexplorer-plugins#17]
在可道云中用onlyoffice编辑后，不能和下载和分享的文件同步，
在线编辑后的文档只能用在线编辑时才保持最新，但是下载下来的文件还是没有变化，分享的文件也没有变，

**Comment by oyzbmmmm** [comment]
因为开了防盗链，开启允许空referer即可

**Comment by cookieY** [comment]
> 因为开了防盗链，开启允许空referer即可

你好 我也遇见了您的这个问题，但在kod中nginx并没有开启防盗链 不知应该如何操作呢  可道云的版本v1.3604

**Comment by 13414897882** [comment]
这是来自QQ邮箱的自动回复邮件。谢谢你的邮件，我会尽快查看

**Comment by oyzbmmmm** [comment]
> > 因为开了防盗链，开启允许空referer即可
> 
> 
> 
> 你好 我也遇见了您的这个问题，但在kod中nginx并没有开启防盗链 不知应该如何操作呢  可道云的版本v1.3604
> 
> 

onlyoffice是docker部署的吗？去docker和反代的网站看日志就知道哪里出问题了

**Comment by cookieY** [comment]
> > > 因为开了防盗链，开启允许空referer即可
> > 
> > 
> > 你好 我也遇见了您的这个问题，但在kod中nginx并没有开启防盗链 不知应该如何操作呢  可道云的版本v1.3604
> 
> onlyoffice是docker部署的吗？去docker和反代的网站看日志就知道哪里出问题了

是docker部署的  进容器后查看了onlyoffice nginx配置文件并未发现防盗链设置 日志中未见错误 蛮奇怪的 - -

**Comment by hyxl520** [comment]
你好，我最近也遇到了这个问题，日志并没有发现什么异常，就是dosc无法保存
