### ISSUE TITLE
大佬 能不能更新支持一下5.0版本的？

### ISSUE THREAD

**Issue by Kenneyzh** [zhtengw/kodexplorer-plugins#3]
5.0版本的好像又改了下结构。。 我对照着改了下json文件，还是不能用

**Comment by 13414897882** [comment]
我把整个插件打包给你，参照一下？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上6:57
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




5.0版本的好像又改了下结构。。 我对照着改了下json文件，还是不能用

**Comment by zhtengw** [comment]
这里有5.0的branch，package.json结构改了，api的很多接口也变了，大部分我都改了，但不保证好用，主要是5.0本身的bug都很多

**Comment by 13414897882** [comment]
我觉得还是等可道云正式版出来了，比较稳定了才弄插件，新版本可道云用的是数据库，我觉得还没有老版本的方便






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上7:05
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




这里有5.0的branch，package.json结构改了，api的很多接口也变了，大部分我都改了，但不保证好用，主要是5.0本身的bug都很多

**Comment by Kenneyzh** [comment]
哦 看到分支了，我来试试~~谢谢

**Comment by 13414897882** [comment]
现在可道云更新到5.09版本了，大神，不好意思，我不会编程




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上7:13
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




哦 看到分支了，我来试试~~谢谢

**Comment by Kenneyzh** [comment]
出错了! (warning!)
Call to undefined function _DIR()

果然不行~

**Comment by 13414897882** [comment]
我在论坛上看到有企业版用户反馈，onlyoffice装不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上7:22
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




出错了! (warning!)
 Call to undefined function _DIR()
 
果然不行~

**Comment by 13414897882** [comment]
试试在5.09这个版本试一下





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上7:22
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




出错了! (warning!)
 Call to undefined function _DIR()
 
果然不行~

**Comment by 13414897882** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上7:22
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




出错了! (warning!)
 Call to undefined function _DIR()
 
果然不行~

**Comment by 13414897882** [comment]
刚刚发错了，发到你的插件了，应该是这个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上7:22
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




出错了! (warning!)
 Call to undefined function _DIR()
 
果然不行~

**Comment by zhtengw** [comment]
刚试了5.09，我这里连文件都建不了，离稳定还有距离。

**Comment by 13414897882** [comment]
群里有很多人测试，等他们测试好了，新的稳定版出来了再折腾吧，现在bug多，也有可能是这个程序本身的问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上8:05
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




刚试了5.09，我这里连文件都建不了，离稳定还有距离。

**Comment by zhtengw** [comment]
@Kenneyzh 5.0分支的onlyoffice感觉改得差不多了，我这里能用了，你试试看

**Comment by zhtengw** [comment]
发现5.0文件路径的函数返回值变了，onlyoffice和photopea目前都没法保存文件。

**Comment by 13414897882** [comment]
先用一段时间，主要是用来预览的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aten Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月1日(星期三) 上午9:52
收件人:&nbsp;"zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送:&nbsp;"落叶飞花"<2717351890@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)




发现5.0文件路径的函数返回值变了，onlyoffice和photopea目前都没法保存文件。

**Comment by 13414897882** [comment]
cad预览图片还是加载不出来

**Comment by zhtengw** [comment]
@13414897882 cad的问题感觉是sharecad.org原因，控制台提示是sharecad.org报500

**Comment by zhtengw** [comment]
@Kenneyzh @13414897882 刚刚更新了5.0分支的onlyoffice和photopea，基本可用了。kod5.0可以用pluginLocalFile函数获得文件的临时缓存的绝对路径，然后还有一个pluginCacheFileSet函数可以解析写入原文件。所以采用先保存修改后的文件到缓存，然后再调用pluginCacheFileSet覆盖原始文件的方式来进行保存。这也导致修改后要等几秒刷新才能看到变化。

**Comment by zhtengw** [comment]
另外，pluginLocalFile函数解析外置存储的文件路径和内置存储的绝对路径有问题，所以kod5.0里面暂时只能用来打开“我的文档”和“企业网盘”里面的文件。有官方人员说这个还会再调整，之后等正式版再看看了。

**Comment by Kenneyzh** [comment]
好的 我来试试

**Comment by Kenneyzh** [comment]
确实能用了，只能打开 我的文档 等路径中的 这确实是新版kod的问题

**Comment by zhtengw** [comment]
@Kenneyzh kod5.11可以升级了，解决了io路径的问题，现在都能打开了。

**Comment by 13414897882** [comment]
你好，我发现onlyoffice插件对手机端的支持不太好，用手机打开office文档滑动滚动条很卡，请问你可以优化一下移动端的预览吗？



---原始邮件---
发件人: "Aten Zhang"<notifications@github.com&gt;
发送时间: 2020年1月3日(周五) 晚上9:44
收件人: "zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"13414897882"<2717351890@qq.com&gt;;
主题: Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)



@Kenneyzh kod5.11可以升级了，解决了io路径的问题，现在都能打开了。

**Comment by zhtengw** [comment]
@13414897882 你试试release页面的版本，手机访问时自动显示wap页面的。如果用那个还觉得不好的话，那我就没办法了，能力不够。

**Comment by 13414897882** [comment]
你好，关于onlyoffice插件，我给了游客编辑保存文件的权限，但是还是无法编辑，请问是不是根据账户的性质，把代码写死了？



---原始邮件---
发件人: "Aten Zhang"<notifications@github.com&gt;
发送时间: 2020年1月5日(周日) 晚上11:03
收件人: "zhtengw/kodexplorer-plugins"<kodexplorer-plugins@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"13414897882"<2717351890@qq.com&gt;;
主题: Re: [zhtengw/kodexplorer-plugins] 大佬 能不能更新支持一下5.0版本的？ (#3)



@13414897882 你试试release页面的版本，手机访问时自动显示wap页面的。如果用那个还觉得不好的话，那我就没办法了，能力不够。

**Comment by zhtengw** [comment]
@13414897882 新开一个issue吧，不是这个主题的，不在这里讨论了。
