### ISSUE TITLE
kodbox 不管是用毕生还是OnlyOffice编辑完过一会就会丢失编辑内容

### ISSUE THREAD

**Issue by coolsd** [zhtengw/kodexplorer-plugins#7]
不知道是为什么，如果多尝试几次直接提示文件不存在了，有人一样的情况吗

**Comment by coolsd** [comment]
txt 格式的没问题。只有office文件格式的才这样

**Comment by zhtengw** [comment]
kodbox更改了文件存取方式，插件无法直接修改原文件，onlyoffice和毕升保存的文件都是先储存到kodbox的文件缓存，再覆盖原文件的，修改关闭之后大概要等待3到5分钟才会对原文件生效，如果回存过程中多次打开修改，可能导致缓存出错。

**Comment by coolsd** [comment]
:( 修改之后马上打开 编辑的内容还在，过个几分钟打开就没了，或者有时候就是文件不存在了。

**Comment by coolsd** [comment]
已经换到KODExplorer了，目前使用正常，请问大佬onlyoffice-api-deploy 怎么修改管理密码呀，后台管理的连接无法打开呀

**Comment by zhtengw** [comment]
可能跟我先将文档回存到缓存有关，处理回存的函数里调整了一下，现在是直接覆盖原文件，不先保存到缓存了，看看还会不会有这个问题。

**Comment by zhtengw** [comment]
回存调整后应该可以避免这个问题了，先关闭issue，如果还遇到可以重开
