### ISSUE TITLE
cdn 远程服务器无法调用的问题

### ISSUE THREAD

**Issue by 1275788667** [zhtengw/kodexplorer-plugins#8]
@zhtengw 
你好 我想咨询下你的这个站点 https://home.aten.ml:4443 是怎么做到远程服务器还能使用的？   我本地搭建好的毕升远程可以访问 但是无法调用  也不能说是远程 是cdn的环境下  你的毕升可以调用 但是我的毕升却无法调用  求解

**Comment by zhtengw** [comment]
我没有使用cdn，自己注册的域名，服务器有公网IP，用he dns解析域名

**Comment by 1275788667** [comment]
@zhtengw 那你部署的这个站点也是毕升免费版本吗  还是是付费版本  我的站点使用cdn之后用你的毕升服务器正常  用我源站机器的cdn就没用了   除非不用cdn

**Comment by zhtengw** [comment]
免费的，访问我的网站跟你的站点有没有使用cdn没关系

**Comment by zhtengw** [comment]
cdn没法加速非常规端口吧，是不是可以在web服务里用子目录转发的办法访问你的毕升站点，我没用过cdn，不大清楚

**Comment by 1275788667** [comment]
@zhtengw 发现问题所在了 无法上传文件  运行命令发现mongodb报错 捣鼓了半天还是没解决  也没搜到有我这种情况的用户 难受

**Comment by 1275788667** [comment]
自己宿主机装了个mongodb开启远程访问解决 哎
